apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: {{ .Values.database.image }}
        env:
        - name: POSTGRES_DB
          value: translations
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data # שונה לנתיב המדויק של המידע
        # --- השינוי כאן: הזרקת הסקריפט לאתחול הטבלה ---
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      # --- השינוי כאן: הגדרת המקור של הסקריפט מתוך ה-ConfigMap ---
      - name: init-script
        configMap:
          name: db-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 5432
  selector:
    app: db